name: Require “Allow Edits”

on: [pull_request_target]

permissions:
  contents: read

jobs:
  _:
    permissions:
      pull-requests: read
    name: "Require “Allow Edits”"

    runs-on: ubuntu-latest

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@2e205a28d0e1da00c5f53b161f4067b052c61f34 # v1.5.0
      with:
        allowed-endpoints:
          api.github.com:443
    - uses: ljharb/require-allow-edits@2bf6dc5607979ae0e3f8739b9f9a4018e024b9a0 # main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
